# Generated by Django 4.2.7 on 2025-10-28 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/', verbose_name='照片')),
                ('bio', models.TextField(verbose_name='个人简介')),
                ('program', models.TextField(verbose_name='竞选纲领')),
                ('party', models.CharField(blank=True, max_length=100, verbose_name='政党')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '候选人',
                'verbose_name_plural': '候选人',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='选举标题')),
                ('description', models.TextField(verbose_name='选举描述')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否活跃')),
            ],
            options={
                'verbose_name': '选举',
                'verbose_name_plural': '选举',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate', verbose_name='候选人')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election', verbose_name='选举')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投票人')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票记录',
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
