# Generated by Django 4.2.7 on 2025-12-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='color',
            field=models.CharField(default='#1e3a8a', max_length=7, verbose_name='代表颜色'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='light_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='浅色'),
        ),
    ]
